pub struct Bump {
    pub nx: usize,
    pub ny: usize,
    pub mx: usize,
    pub my: usize,
    pub maxnew: usize,
    pub maxsec: usize,

    pub maxrow: usize,
    pub nelemn: usize,
    pub maxeqn: usize,
    pub n_points: usize,

    pub anew: f64,
    pub anext: f64,
    pub aold: f64,
    pub aprof: f64,
    pub iwrite: u8,
    pub _long: bool,
    pub nband: usize,
    pub neqn: usize,
    pub nlband: usize,
    pub nrow: usize,
    pub numnew: usize,
    pub numsec: usize,
    pub reynld: f64,
    pub rjpnew: f64,
    pub rjpold: f64,
    pub tolnew: f64,
    pub tolsec: f64,
    pub xbleft: f64,
    pub xbrite: f64,
    pub xlngth: f64,
    pub xprof: f64,
    pub ylngth: f64,
    pub ypert: f64,

    pub area: Vec<f64>,
    pub dcda: Vec<f64>,
    pub a: Vec<f64>,
    pub f: Vec<f64>,
    pub g: Vec<f64>,
    pub gr: Vec<f64>,
    pub iline: Vec<i32>,
    pub iline_inv: Vec<i32>,
    pub indx: Vec<i32>,
    pub insc: Vec<i32>,
    pub isotri: Vec<i32>,
    pub node: Vec<usize>,
    pub phi: Vec<f64>,
    pub psi: Vec<f64>,
    pub r: Vec<f64>,
    pub res: Vec<f64>,
    pub sens: Vec<f64>,
    pub uprof: Vec<f64>,
    pub xc: Vec<f64>,
    pub xm: Vec<f64>,
    pub yc: Vec<f64>,
    pub ym: Vec<f64>,

    pub save_times: bool,
}

impl Bump {
    pub fn new(nx: usize, ny: usize, mx: usize, my: usize) -> Self {
        let maxrow: usize = 27 * ny;
        let nelemn: usize = 2 * (nx - 1) * (ny - 1);
        let maxeqn: usize = 2 * mx * my + nx * ny;
        let n_points: usize = mx * my;
        Self {
            nx,
            ny,
            mx,
            my,
            maxnew: 4,
            maxsec: 10,

            maxrow,
            nelemn,
            maxeqn,
            n_points,

            anew: 0.0,
            anext: 0.3,
            aold: 0.0,
            aprof: 0.25,
            iwrite: 10,
            _long: false,
            nband: 0,
            neqn: 0,
            nlband: 0,
            nrow: 0,
            numnew: 0,
            numsec: 0,
            reynld: 1.0,
            rjpnew: 0.0,
            rjpold: 0.0,
            tolnew: 0.0001,
            tolsec: 0.0001,
            xbleft: 1.0,
            xbrite: 3.0,
            xlngth: 10.0,
            xprof: 4.0,
            ylngth: 3.0,
            ypert: 0.0,

            area: vec![0.0; nelemn],
            dcda: vec![0.0; my],
            a: vec![0.0; 1],
            f: vec![0.0; 1],
            g: vec![0.0; 1],
            gr: vec![0.0; my * my],
            iline: vec![0; my],
            iline_inv: Vec::new(),
            indx: vec![0; n_points * 2],
            insc: vec![0; n_points],
            isotri: vec![0; nelemn],
            node: vec![0; nelemn * 6],
            phi: vec![0.0; nelemn * 3 * 6 * 3],
            psi: vec![0.0; nelemn * 3 * 6],
            r: vec![0.0; my],
            res: vec![0.0; 1],
            sens: vec![0.0; 1],
            uprof: vec![0.0; my],
            xc: vec![0.0; n_points],
            xm: vec![0.0; nelemn * 3],
            yc: vec![0.0; n_points],
            ym: vec![0.0; nelemn * 3],

            save_times: true,
        }
    }
}
